- name: install ubuntu packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dstat
    - golang
    - htop
    - net-tools
    - sysstat
    - percona-toolkit # for pt-query-digest

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: put bash aliases
  copy:
    src: .bash_aliases
    dest: ~/.bash_aliases
    mode: 0644
  become: false

- name: put bash aliases (root)
  copy:
    src: .bash_aliases
    dest: /root/.bash_aliases
    mode: 0644
