- name: install ubuntu packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dstat
    - golang
    - htop
    - net-tools
    - sysstat
    - percona-toolkit # for pt-query-digest

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: put profile files
  copy:
    src: "{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    mode: 0644

  loop:
    - 1000_env.sh
    - 1001_aliases.sh
