- name: install ubuntu packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dstat
    - golang
    - htop
    - net-tools
    - sysstat
    - percona-toolkit # for pt-query-digest
