---
all:
  children:
    web:
      hosts:
        isu1:
        # isu2:
        # isu3:
    db:
      hosts:
        # isu1:
        isu2:
        # isu3:
    app:
      hosts:
        # isu1:
        # isu2:
        # isu3:

  hosts:
    isu1:
      ansible_host: 54.199.34.186
      ansible_user: isucon
    isu2:
      ansible_host: 13.114.161.39
      ansible_user: isucon
    isu3:
      ansible_host: 13.231.210.201
      ansible_user: isucon
