- name: backup files
  copy:
    src: "{{ item }}"
    dest: "{{ item }}_{{ now(fmt='%H:%M:%S') }}"
    remote_src: yes
  changed_when: False
  loop:
    - /etc/mysql/my.cnf

- name: copy mysql configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
    - restart mysql
  loop:
    - { src: my.cnf, dest: /etc/mysql/my.cnf }

- name: move files if exists
  command: mv {{ item.src }} {{ item.dest }}
  loop:
    - {
        src:  /var/log/mysql/mysqld-slow.log,
        dest: "/var/log/mysql/mysqld-slow.log_{{ now(fmt='%H:%M:%S') }}"
      }
  changed_when: False
  ignore_errors: yes
