- name: backup files
  copy:
    src: "{{ item }}"
    dest: "{{ item }}_{{ now(fmt='%H:%M:%S') }}"
    remote_src: yes
  changed_when: False
  loop:
    - /etc/mysql/my.cnf
    - /var/log/mysql/mysqld-slow.log


- name: copy mysql configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
    - restart mysql
  loop:
    - { src: my.cnf, dest: /etc/mysql/my.cnf }
