- name: web
  hosts: web
  roles:
    - nginx
  tasks:
    - name: stop mysql
      service:
        name: mysql
        state: stopped
        enabled: no

- name: db
  hosts: db
  roles:
    - mysql
  tasks:
    - name: stop nginx
      service:
        name: nginx
        state: stopped
        enabled: no
