- name: all
  hosts: all
  roles:
    - {name: common, tags: common}

- name: web
  hosts: web
  roles:
    - {name: nginx, tags: nginx}

- name: db
  hosts: db
  roles:
    - {name: mysql, tags: mysql}

- name: app
  hosts: app
  roles:
    - {name: app, tags: app}


# ---- 停止系 ----

- name: no_web
  hosts: no_web
  tasks:
    - name: stop nginx
      service:
        name: nginx
        state: stopped
        enabled: no

- name: no_db
  hosts: no_db
  tasks:
    - name: stop mysql
      service:
        name: mysql
        state: stopped
        enabled: no

- name: no_app
  hosts: no_app
  tasks:
    - name: stop app
      service:
        name: isu-go
        state: stopped
        enabled: no
